// Generated by CoffeeScript 1.6.3
(function() {
  var fs, html, http, port, server;

  port = process.env.PORT || 5000;

  http = require('http');

  fs = require('fs');

  html = fs.readFileSync('./resize.html', 'utf8');

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      "Content-Type": "text/html"
    });
    return res.end(html);
  }).listen(port);

  console.log("Image Resize Server Running on localhost:" + port);

}).call(this);
